### ISSUE TITLE
[Discussion]: Add + Organize language specific Examples and Implementations

### ISSUE THREAD

**Issue by JDSherbert** [VerzatileDevOrg/Programming_HandBook#25]
While we currently have some examples in our "Concepts" folder, it would make sense to include different language's examples rather than defaulting to whatever is easiest (where applicable, as some languages do not utilize certain concepts, for example OOP).
Discuss:

* Default language for examples
* Folder structure and organization (do we want to duplicate pages but with language specific examples)
* See if there is a way to implement multiple language examples on the same page? (Maybe a dropdown to swap to that language)

**Comment by VerzatileDev** [comment]
I Have Figured this one out here is an example how it works currently:
![image](https://github.com/VerzatileDevOrg/Programming_HandBook/assets/47317248/98163cb1-10fe-4de7-b1c2-52e1a145db16)


Though this should be made globally accessible features changing these into " JavaScript file " and Storing it either as a cookie or memory to Remember what option was clicked, Additionally that means, the default should  be listed, currently it should stay  under the " c++ " content by default, though I donät think on the live server it would remember it when the page gets refreshed. 

I have done this in the following way:

`
---
layout: default
title: OOP
nav_order: 1
parent: Concepts
has_children: false
---

{{ page.title }}
======================

{% include under_construction.html %}

<div id="cppContent">
  
  This is C++ content for Object-Oriented Programming.
</div>

<div id="csharpContent" style="display:none;">
  
  This is C# content for Object-Oriented Programming.
</div>

<button onclick="showContent('cpp')">C++</button>
<button onclick="showContent('csharp')">C#</button>

<script>
  function showContent(language) {
    if (language === 'cpp') {
      document.getElementById('cppContent').style.display = 'block';
      document.getElementById('csharpContent').style.display = 'none';
    } else if (language === 'csharp') {
      document.getElementById('cppContent').style.display = 'none';
      document.getElementById('csharpContent').style.display = 'block';
    }
  }
</script>
`

**Comment by VerzatileDev** [comment]
I have added another method to the feature " https://github.com/VerzatileDev/Programming_HandBook/tree/main  "on my specific fork branch.

Additionally added a feature that adds an event listener and saves the current language to the users local storage, if not defiend previously.

If it is defined it loads the selected language from this example Cpp or Csharp.

Which will be asked each time a refresh is called or page is reloaded.

Additionally Pressing the Button either cpp or Csharp will rewrite the Language Preference and store it to locally.

Note:

This Requires that the JavaScript would be made globally not for each instance where possible.

Make sure that only specified buttons are called so make cases if there are less or more languages.

" in the future figure out where to store these as all in the same file would be an overkill potentially ".

**Comment by VerzatileDev** [comment]
See the following addressed in the pull request " https://github.com/VerzatileDevOrg/Programming_HandBook/pull/68 " Language Specific examples. The following addresses the issue in a basic way as a concept of how it could be handled, though would require it to be accessible globally, which requires a selection of what types are shown based on the available " <div Id " defined in the .md file.
