### ISSUE TITLE
"Child of Child "Content

### ISSUE THREAD

**Issue by VerzatileDev** [VerzatileDevOrg/Programming_HandBook#34]
Issue:
- When creating content as child such as example.md that itself derives from a parent, which has a Child 
- it is not displayed as part of the first child.

Example:
Parent -> Child -> Child   <-- (Issue with the following)

Shows  Parent -> Child -> (Shows That it has children, but won't show them).

**Comment by VerzatileDev** [comment]
It seems with an official fully developed Site uses Permalinks to get around the issue of " Child of Child " 
![image](https://github.com/VerzatileDevOrg/Programming_HandBook/assets/47317248/f1c4204b-1461-4d55-a3d0-35b654d2d96c)

Reference of image.
https://github.com/just-the-docs/just-the-docs/blob/main/docs/ui-components/line-nos.md?plain=1

As seen here on the official page>
https://just-the-docs.com/docs/ui-components/code/line-numbers/

**Comment by JDSherbert** [comment]
Would be interesting if we can get that to work!

**Comment by VerzatileDev** [comment]
Issue can be resolved by:
----------------------------
Parent (Enable Children true)
Child of Parent (Enable Children true) (parent: Parent)
Child of Child of Parent (Enable Children true) (parent: Child of Parent) (grandparent: Parent ).

Language (Parent aka GrandParent) -> C++ (Child)-> Pointer (Child of Child)

Pointer as Reference:

`---
layout: default
title: Pointers
nav_order: 1
parent: C++
grand_parent: Language
has_children: false
---`
