### ISSUE TITLE
[ADDRESS] Child in Child in Child Content

### ISSUE THREAD

**Issue by VerzatileDev** [VerzatileDevOrg/Programming_HandBook#61]
**Description:**

Currently the possibility is to have a parent, that has a child. And a Grandparent that has a parent with a child.

Though there is no Parent of Grandparent of parent of child method available.

**Proposed Solution:**

Look into solving the following issue, see if there are hint of this within the official documentation site and or if it is supported.

**Alternatives:**

If it is not supported look into coding the part to support it.

**Additional Context**

-none.

**Comment by VerzatileDev** [comment]
Found more Explanation and references to the following issue:
https://just-the-docs.com/docs/navigation-structure/#children-with-children

**Comment by VerzatileDev** [comment]
Here is some addressing for " grand grand parent " https://docs.metasploit.com/docs/modules.html  
![image](https://github.com/VerzatileDevOrg/Programming_HandBook/assets/47317248/48233664-f80a-4f1d-a9e8-31e76560f650)

Also this New theme built on it looks interesting " https://www.docsy.dev/docs/best-practices/ " 

As well as this would be interesting to take a look at " https://docusaurus.io/docs " 

This.. " https://github.com/just-the-docs/just-the-docs/pull/462 " 

Additionally going to add this " https://squidfunk.github.io/mkdocs-material/getting-started/ " it has good features that we could take interest in.

**Comment by VerzatileDev** [comment]
They are looking to address this in the next update possibly. But as it stands it most likely will be denied and has to be implemented ourselves. There was an interesting topic that they wanted to do it with " ID s " which would make more sense to organize and change how much code is required to add pages and modify them, but as there are over 10k pages reliying on it they cannot do that as companies except to also simply update it to the latest version and such.

**Comment by VerzatileDev** [comment]
Is there a requirement at the current moment to implement the following feature?

- Would be able to take a look into it.

**Comment by JDSherbert** [comment]
> Is there a requirement at the current moment to implement the following feature?
> 
> * Would be able to take a look into it.

It's worth adding if you can make it scalable. Consider:

Docs/Content/IDE/VisualStudio/Compiler/Clang or something along that line, where there are going to be subcontent within subcontent.

**Comment by VerzatileDev** [comment]
Still quite an issue especially for 

![image](https://github.com/user-attachments/assets/47559ba3-fd9a-4909-a559-05bd03c3a7fc)

VersionControl -> Git -> github -> ...

**Comment by VerzatileDev** [comment]
HyperLink shows it correctly, so the issue is more or less with the list itself 

![image](https://github.com/user-attachments/assets/eb954989-1a6e-48fc-a11d-f80e4ba8b29d)

**Comment by VerzatileDev** [comment]
The latest " Just the docs v0.10.0 " includes and adds the availability for infinite addition of content.

As shown here 

![image](https://github.com/user-attachments/assets/43abb39b-243d-4070-a7a5-744e9d1ae18b)


The following Branch on another repository suggests what to add in the PR request.
